Update the rest-client gem
2.0.0 contained a bug that caused the following error on OpenSSL 1.1.0+

    KeyError: key not found: :ciphers

https://github.com/rest-client/rest-client/issues/569